name = "nist_hdf5"
description = ""
version = "0.1.0-dev"

authors = ["Roger"]
maintainers = ["Roger <rogermc@iinet.net.au>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["main"]
